# Generated by Django 6.1.1 on 2026-09-23 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True)),
                ('label', models.CharField(max_length=40)),
                ('intro', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('recognize', 'Recognize'), ('decide', 'Decide'), ('report', 'Report'), ('recovery', 'If it already happened')], default='decide', max_length=20)),
                ('prompt', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='scenarios/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='cybergame.grade')),
            ],
            options={
                'ordering': ['grade__number', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('points', models.PositiveSmallIntegerField(default=0)),
                ('feedback', models.TextField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='cybergame.scenario')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
