# Generated by Django 6.1.1 on 2026-09-24 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cybergame', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='emoji',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='scenario',
            name='art',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='scenario',
            name='kind',
            field=models.CharField(choices=[('chat', 'Chat message'), ('popup', 'Pop-up'), ('voice', 'Voice message'), ('ask', 'Plain question')], default='ask', max_length=10),
        ),
        migrations.AddField(
            model_name='scenario',
            name='question',
            field=models.CharField(default='What do you do?', max_length=80),
        ),
        migrations.AddField(
            model_name='scenario',
            name='sender',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='scenario',
            name='sender_emoji',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
